export const elements = {
   signUp: document.querySelector('.btn--signup'),
   signIn: document.querySelector('.btn--signin'),
   signOut: document.querySelector('.btn--signout'),
   overlay: document.querySelector('.overlay'),
   formSignUp: document.querySelector('.form--signup'),
   formSignIn: document.querySelector('.form--signin'),
   exitForm: document.querySelector('.form__exit'),
   search: document.querySelector('.search'),
   searchLocation: document.querySelector('.search__input--location'),
   searchRating: document.querySelector('.search__input--rating'),
   cards: document.querySelector('.cards'),
   results: document.querySelector('.results'),
   signUpForm: document.querySelector('.form--signup'),
   signUpName: document.querySelector('.form__input--name'),
   signUpEmail: document.querySelector('.form__input--email-up'),
   signUpPassword: document.querySelector('.form__input--password-up'),
   signInForm: document.querySelector('.form--signin'),
   signInEmail: document.querySelector('.form__input--email-in'),
   signInPassword: document.querySelector('.form__input--password-in'),
}